# Generated by Django 3.2.3 on 2021-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.TextField(default='Account Name', max_length=150, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.TextField(default='Account Number', max_length=150, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.TextField(default='Bank', max_length=150, verbose_name='Bank Name'),
        ),
    ]
