# Generated by Django 3.2.3 on 2021-06-10 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210608_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.TextField(max_length=20, null=True, verbose_name='Sending Party')),
                ('to_id', models.TextField(max_length=20, null=True, verbose_name='Recieving Party')),
                ('transaction_type', models.TextField(max_length=20, null=True, verbose_name='Type of Transaction')),
                ('transaction_message', models.TextField(max_length=500, null=True, verbose_name='Message')),
                ('amount', models.FloatField(null=True, verbose_name='Amount Sent')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Transaction Table',
            },
        ),
        migrations.DeleteModel(
            name='AccountDetails',
        ),
    ]
