# Generated by Django 3.2.3 on 2021-07-09 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(max_length=20, null=True, verbose_name='Client ID')),
                ('sp_id', models.TextField(max_length=20, null=True, verbose_name='Service Provider ID')),
                ('budget', models.CharField(max_length=500, null=True, verbose_name='Client Budget')),
                ('service_type', models.TextField(max_length=500, null=True, verbose_name='Type of Services/Job')),
                ('commission', models.CharField(default=0, max_length=500, null=True, verbose_name="Vista's Commission")),
                ('dispute', models.BooleanField(default=False, verbose_name='Did Client raise dispute')),
                ('isPaid', models.BooleanField(default=False, verbose_name='Was payment made to Service Provider')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Escrow_table',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(max_length=20, null=True, verbose_name='Client ID')),
                ('sp_id', models.TextField(max_length=20, null=True, verbose_name='Service Provider ID')),
                ('budget', models.CharField(max_length=500, null=True, verbose_name='Client Budget')),
                ('service_type', models.TextField(max_length=500, null=True, verbose_name='Type of Services/Job')),
                ('sp_reject_id', models.TextField(max_length=500, null=True, verbose_name='Service Provider ID')),
                ('isTaken', models.BooleanField(default=False, verbose_name='is the Job taken by an SP')),
                ('isRejectedSP', models.BooleanField(default=False, verbose_name='Did the first SP rejected the Job')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Did SP finish the Job')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Services_table',
            },
        ),
    ]
