# Generated by Django 3.2.3 on 2021-07-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210709_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='engaged',
            field=models.BooleanField(default=False, verbose_name='Is the SP currently doing a job'),
        ),
    ]
