# Generated by Django 3.2.3 on 2021-07-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_engaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='job_id',
            field=models.TextField(max_length=20, null=True, verbose_name='Job ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sp_reject_id',
            field=models.TextField(max_length=500, null=True, verbose_name='Service Provider ID who rejected job'),
        ),
    ]
