# Generated by Django 3.2.3 on 2021-07-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210724_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='budget',
            field=models.FloatField(max_length=500, null=True, verbose_name='Client Budget'),
        ),
        migrations.AlterField(
            model_name='services',
            name='budget',
            field=models.FloatField(max_length=500, null=True, verbose_name='Client Budget'),
        ),
    ]
