# Generated by Django 3.2.3 on 2021-08-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210724_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='services',
            name='details',
        ),
        migrations.RemoveField(
            model_name='services',
            name='tools',
        ),
        migrations.AddField(
            model_name='services',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='services',
            name='amount',
            field=models.FloatField(max_length=500, null=True, verbose_name='Service Charge'),
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=10500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='services',
            name='payment_mode',
            field=models.CharField(max_length=500, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_form',
            field=models.CharField(max_length=500, null=True, verbose_name='Service Type/form'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_online',
            field=models.BooleanField(default=False),
        ),
    ]
