# Generated by Django 3.2.3 on 2021-08-17 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210813_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(max_length=500, null=True, verbose_name='Service')),
                ('type', models.CharField(max_length=500, null=True, verbose_name='Type of Services')),
                ('amount', models.FloatField(null=True, verbose_name='Price/Unit Service')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Service Category and Pricing',
            },
        ),
        migrations.AddField(
            model_name='services',
            name='specific_service',
            field=models.CharField(max_length=500, null=True, verbose_name='Exact Service'),
        ),
        migrations.AddField(
            model_name='services',
            name='unit',
            field=models.CharField(max_length=500, null=True, verbose_name='Quantity/Unit per Service'),
        ),
    ]
