# Generated by Django 3.2.3 on 2021-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210817_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='payment_mode',
            field=models.CharField(max_length=500, null=True, verbose_name='Payment Mode'),
        ),
    ]
