# Generated by Django 3.2.3 on 2021-08-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_escrow_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
