# Generated by Django 3.2.3 on 2021-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(default='6.6363701', max_length=500, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default='3.3405270', max_length=500, verbose_name='Longitude'),
        ),
    ]
