# Generated by Django 3.2.3 on 2021-09-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210910_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owingVistaCommission',
            field=models.BooleanField(default=False, verbose_name='Has SP paid the comissioned owed'),
        ),
    ]
