# Generated by Django 3.2.3 on 2021-09-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_owingvistacommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(max_length=30, null=True, verbose_name='BVN')),
                ('nin', models.CharField(max_length=30, null=True, verbose_name='NIN')),
                ('idCard', models.CharField(max_length=500, null=True, verbose_name='ID Card')),
                ('passport', models.CharField(max_length=500, null=True, verbose_name='Photo Passport')),
                ('proofOfAddress', models.FileField(max_length=30, null=True, upload_to='', verbose_name='Proof of Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'SPs Verification Documents',
            },
        ),
    ]
