# Generated by Django 3.2.3 on 2021-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_verificationdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocuments',
            name='proofOfAddress',
            field=models.CharField(max_length=30, null=True, verbose_name='Proof of Address'),
        ),
    ]
