# Generated by Django 3.2.8 on 2021-12-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocuments',
            name='proofOfAddress',
            field=models.CharField(max_length=3000, null=True, verbose_name='Proof of Address'),
        ),
    ]
