# Generated by Django 3.2.8 on 2022-03-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
