# Generated by Django 3.2.8 on 2022-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='isDirectedToAdmin',
            field=models.BooleanField(default=False, verbose_name='is a Special service requiring Admin to connect client with SP'),
        ),
    ]
