# Generated by Django 3.2.8 on 2022-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_services_isdirectedtoadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='services',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='services',
            name='amount',
            field=models.FloatField(blank=True, max_length=500, null=True, verbose_name='Service Charge Amount'),
        ),
        migrations.AlterField(
            model_name='services',
            name='client_id',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(blank=True, max_length=10500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='services',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_form',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Service Type/form'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Type of Services/Job'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sp_id',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Service Provider ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sp_reject_id',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Service Provider ID who rejected job'),
        ),
        migrations.AlterField(
            model_name='services',
            name='specific_service',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Exact Service'),
        ),
        migrations.AlterField(
            model_name='services',
            name='unit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Quantity/Unit per Service'),
        ),
        migrations.AlterField(
            model_name='verificationdocuments',
            name='bvn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='BVN'),
        ),
        migrations.AlterField(
            model_name='verificationdocuments',
            name='idCard',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID Card'),
        ),
        migrations.AlterField(
            model_name='verificationdocuments',
            name='nin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NIN'),
        ),
        migrations.AlterField(
            model_name='verificationdocuments',
            name='passport',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Photo Passport'),
        ),
        migrations.AlterField(
            model_name='verificationdocuments',
            name='proofOfAddress',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Proof of Address'),
        ),
    ]
