# Generated by Django 3.2.13 on 2022-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220327_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Payee Name')),
                ('user_id', models.CharField(max_length=500, verbose_name='Payee ID')),
                ('message', models.TextField(max_length=500, null=True, verbose_name='Message')),
                ('amount', models.FloatField(blank=True, max_length=1000, verbose_name='Amount Transacted')),
                ('email', models.CharField(default='none', max_length=500, verbose_name='Email')),
                ('paidByAdmin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'db_table': 'Withdrwala or Payment request_table',
            },
        ),
    ]
